language: node_js
script:
  - npm install -g surge
  - sudo chmod +x getversion.sh
  - ./getversion.sh
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master